.PHONY: dev prod

dev:
	@npm run dev

prod:
	@npm run build
	@npm preview

help:
	@echo "Usage: make [dev|prod]"
	@echo ""
	@echo "  dev:  Start the client in development mode"
	@echo "  prod: Build and start the client in production mode"
